name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './zora-coin-creator/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./zora-coin-creator
      
      - name: Build
        run: npm run build
        working-directory: ./zora-coin-creator
        env:
          VITE_ZORA_API_KEY: ${{ secrets.VITE_ZORA_API_KEY }}
      
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Make result dir
        run: mkdir -p ./output
      
      - name: Move output file
        run: mv ./zora-coin-creator/dist ./output/zora-coin-creator
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './output'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4